### ISSUE TITLE
Please tag release in Git

### ISSUE THREAD

**Issue by sunweaver** [pvdz/ZeParser#16]
Hi,

I am about to package this source project for Debian. I'd appreciate if releases got tagged in this Git repositories, so that it is much easier to keep track of new versions to package.

Thanks+Greets,
Mike (aka sunweaver@debian.org)

**Comment by pvdz** [comment]
Will version 1.0 suffice? 

Btw I've moved on to zeparser2 (but if somebody has an issue I'll take a look at it :)

**Comment by sunweaver** [comment]
Hi,

your package.json file says it is 0.0.5. If you have changed things after that release, then release 0.0.6 (if appropriate) and tag it as 0.0.6.

As people use ZeParser (not ZeParser2) as dependency (i.e. the active-x-obfuscator module), I need ZeParser as is.

Thanks+Greets,
Mike

**Comment by pvdz** [comment]
Oh that's nice. Sure, I'll add a tag for v0.0.6 (somebody else made package.json at the time because he needed it). Be sure to exclude the 8mb test file in the downloadble package... :)

**Comment by pvdz** [comment]
Tag added.

**Comment by pvdz** [comment]
(https://github.com/qfox/ZeParser/tree/v0.0.6)
