### ISSUE TITLE
Update version in package.json

### ISSUE THREAD

**Issue by sunweaver** [pvdz/ZeParser#17]
Hi,

with the 0.0.6 tag you forgot to adapt the version in package.json. For 0.0.7 make sure you tag _and_ increment the version in package.json.

Greets,
Mike

**Comment by pvdz** [comment]
Oh, wasn't aware package.json was relevant for you as well. Will do.

**Comment by pvdz** [comment]
Done: https://github.com/qfox/ZeParser/tree/v0.0.7
