### ISSUE TITLE
npmignore benchmark.html 

### ISSUE THREAD

**Issue by mukundha** [pvdz/ZeParser#18]
Hello,

can  benchmark.html (8mb) be added to .npmignore, this will greatly help reduce the size of the apps using this module

thanks,

**Comment by pvdz** [comment]
That file should be ignored by the `*.html` rule in the current `.npmignore`. Isn't it?

**Comment by felixrabe** [comment]
It is. Probably a dependant package has an explicit dependency on an older version. Cf. #19. @mukundha can you verify which package uses the old zeparser version?

**Comment by pvdz** [comment]
This is a dupe of #19
