### ISSUE TITLE
benchmark.html taking up half of node_modules space

### ISSUE THREAD

**Issue by felixrabe** [pvdz/ZeParser#19]
I've installed `npm install socket.io`, and found that the resulting node_modules was 15 MB in size, of which benchmark.html alone takes up half. If you could exclude it from npm install, that would be awesome.

**Comment by pvdz** [comment]
As you can see `*.html` is ignored through `.npmignore`. Alternative proposals?

**Comment by felixrabe** [comment]
I figured it out. You haven't excluded it in your version 0.0.5 yet, and ZeParser 0.0.5 is an explicit dependency of socket.io via active-x-obfuscator in the following way (just showing the path):

```
node_modules/socket.io/node_modules/socket.io-client/node_modules/active-x-obfuscator/node_modules/zeparser
```

I'll refile the issue there. Thank you.

**Comment by felixrabe** [comment]
Hm, that won't do. https://npmjs.org/package/zeparser shows that 0.0.5 is the latest released version. Also, I don't know whether active-x-obfuscator would work with 0.0.7.

**Comment by felixrabe** [comment]
Reopening as a request to update the npm repo to 0.0.7.

**Comment by pvdz** [comment]
Ping @ehd and @felixge, they did the npm packaging.

**Comment by felixge** [comment]
@qfox totally forgot about that. Just pushed 0.0.7 into the registry.See https://github.com/felixge/node-active-x-obfuscator/issues/5

**Comment by pvdz** [comment]
Great. So this can be closed. Thanks

**Comment by felixrabe** [comment]
Awesome. Thank you.
