### ISSUE TITLE
Please exclude benchmark.html fron npm package

### ISSUE THREAD

**Issue by timbertson** [pvdz/ZeParser#22]
This file is singlehandedly doubling the size of socket.io when installed via `npm`, and presumably has no use in an npm package

**Comment by pvdz** [comment]
That's probably why it's excluded in `.npmignore`, wouldn't you say?

**Comment by timbertson** [comment]
Ahh, sorry about that - I didn't notice that active-x-obfuscator (used by socket.io) is depending specifically on zeparser 0.0.5, which was released before this got ignored. My apologies.

**Comment by pvdz** [comment]
Yeah, it was reported and fixed. Either you've got an older version of it, or it never updated to the newer release. But knowing felix, that's not likely... :0

**Comment by timbertson** [comment]
Yup, I think it must be somewhere upstream - it's pretty nested (`node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/active-x-obfuscator/node_modules/zeparser/`)
