### ISSUE TITLE
GPL code in benchmark.html doesn't match license

### ISSUE THREAD

**Issue by jarthorn** [pvdz/ZeParser#24]
Your repository LICENSE says it is MIT licensed, but there is a bunch of GPL licensed code in benchmark.html. It is potentially harmful to claim one license and then expose consumers to completely different licenses in the code. You should either make it clear that part of your source is GPL licensed in your LICENSE file, or remove the differently licensed code from your source tree.

**Comment by pvdz** [comment]
Benchmark is and was never supposed to be part of distribution.
