### ISSUE TITLE
Ignore .HTML files in npm package

### ISSUE THREAD

**Issue by tomap** [pvdz/ZeParser#29]
Hi,

Could you include .html files in .npmignore to produce a smaller npm package?

Thank you

**Comment by pvdz** [comment]
I'm not going to change anything regarding this package. (And I don't control the npm package, but that's a minor issue)

This package is old, super slow, and deprecated by v2 (https://github.com/qfox/zeparser2). Please use that instead.

Closing this issue as a wontfix.
