### ISSUE TITLE
Duplicate `default` clauses in `switch` statements

### ISSUE THREAD

**Issue by ghost** [pvdz/ZeParser#6]
`ZeParser.parse('switch({}){default: console.log("Yes");break;default: console.log("Yes");break;}', true);` shouldn't parse correctly, but instead returns an array of 31 tokens. I believe [line 1476](https://github.com/qfox/ZeParser/blob/master/ZeParser.js#L1476) should be changed to read:

``` js
while (match.value == 'case' || !stack.parsedSwitchDefault &&
  (stack.parsedSwitchDefault = match.value == 'default')) {
```

(I didn't submit a pull request in case I misinterpreted your code...but I can certainly do so if you can confirm that this is, indeed, the correct fix).

**Comment by pvdz** [comment]
It does seem as if parsedSwitchDefault is not set anywhere. Thanks for the report :D

I'll quickly fix that and add a test.

**Comment by pvdz** [comment]
Fixed and committed
